### ISSUE TITLE
Missing mail_draft icon

### ISSUE THREAD

**Issue by thebodzio** [PapirusDevelopmentTeam/papirus-claws-mail-theme#2]
There's a missing icon for “save to draft folder” button in compose window. Judging by the stock_pixmap.h file the proper name for the icon file should be “mail_draft” (stock_pixmap.h has STOCK_PIXMAP_MAIL_DRAFT defined).

**Comment by varlesh** [comment]
Thx for report, added

**Comment by thebodzio** [comment]
That was lightning fast—thank you! 😄
