### ISSUE TITLE
openSUSE package

### ISSUE THREAD

**Issue by GriefNorth** [PapirusDevelopmentTeam/papirus-claws-mail-theme#4]
Hello, this is link for openSUSE(Leap 42.2, 42.3 and Tumbleweed) package http://software.opensuse.org//download.html?project=home%3AGNorth%3AArc_and_Papirus&package=papirus-claws-mail-theme
My name is Alexander Postol and my OBS link https://build.opensuse.org/package/show/home:GNorth:Arc_and_Papirus 
This repo also contain :
arc-theme
arc-xfce4-terminal-theme
papirus-claws-mail-theme
papirus-filezilla-theme
papirus-icon-theme
papirus-libreoffice-theme
papirus-smplayer-theme

**Comment by SmartFinn** [comment]
Thanks :+1:
