### ISSUE TITLE
Tray icons are semi-transparent

### ISSUE THREAD

**Issue by renyhp** [PapirusDevelopmentTeam/papirus-claws-mail-theme#8]
There is some transparency in the tray icons, which, if I'm not wrong, doesn't fit with the other Papirus icons that are totally opaque.

EDIT: I'm sorry, they are not in fact transparent, however their colour is still not the same for the other Papirus icons. Screenshot attached.
![2020-10-18_19-38](https://user-images.githubusercontent.com/20142663/96375500-a3196e80-1179-11eb-9c34-90d9da833486.png)

**Comment by varlesh** [comment]
updated
